###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '8081:8025'

    redis:
        image: 'redis:alpine'

    mysql:
        image: 'mysql:8.0'
        volumes:
            - './phpdocker/mysql/data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=eCommerceDB
            - MYSQL_USER=eCommerce
            - MYSQL_PASSWORD=password
        ports:
            - '8082:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini'
